version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"

  omeroserver-readwrite:
    # This container uses the tag for the latest server release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    image: "openmicroscopy/omero-server:5"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4064"
    volumes:
      - "omero:/OMERO"

  omeroserver-readonly:
    # This container uses the tag for the latest server release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    image: "openmicroscopy/omero-server:5"
    environment:
      # TODO: setup read-only user in postgresql
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      ROOTPASS: omero
      CONFIG_omero_cluster_read__only: "true"
      CONFIG_omero_pixeldata_memoizer_dir_local: "/tmp/BioFormatsCache"
    networks:
      - omero
    ports:
      - "4064"
    volumes:
      - "omero:/OMERO:ro"
    depends_on:
      - "database"
      - "omeroserver-readwrite"
      - "omeroweb"
      # Wait as long as possible though it may be necessary
      # to restart readonly if it fails on DB creation.

  omeroweb:
    # This container uses the tag for the latest web release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    image: "openmicroscopy/omero-web-standalone:5"
    environment:
      CONFIG_omero_web_server__list: '[["omeroserver-readonly", 4064, "read-only"], ["omeroserver-readwrite", 4064, "read-write"]]'
    networks:
      - omero
    ports:
      - "4080:4080"

networks:
  omero:

volumes:
  database:
  omero:
